```{r}
library(readxl)
library(dplyr)
library(tidyr)
```

```{r}
# Read the Excel file
data <- read_excel("data/raw/WEO_Data.xlsx", col_types = "text")

# Replace "n/a" and blank cells with NA, and convert year columns to numeric
data_cleaned <- data %>%
  select(-Units, -Scale) %>%  
  mutate(across(everything(), ~ na_if(., "n/a"))) %>%  # Replace "n/a" with NA
  mutate(across(starts_with("20"), as.numeric))

# Pivot the data to make it wide
data_wide <- data_cleaned %>%
  pivot_longer(cols = starts_with("20"),
               names_to = "Year", 
               values_to = "Value") %>%
  pivot_wider(names_from = `Subject Descriptor`, 
              values_from = "Value")
```

```{r}
# Read the country status dataset
country_status <- read.csv("data/raw/IMF_country_status.csv")

# Merge IMF data with country status to add "developing" column
imf_data <- data_wide %>%
  left_join(country_status, by = "Country")

# Export the merged data to a CSV file
write.csv(imf_data, file = "data/interim/IMF_data.csv", row.names = FALSE)
```

